### ISSUE TITLE
Màj au schéma IRVE v2

### ISSUE THREAD

**Issue by deuzeffe** [Jungle-Bus/ref-EU-EVSE#1]
Bonjour,

En lisant le code de l'analyse osmose, il semble qu'il fait appel à la ressource ici présente. Pour laquelle je n'ai pas trouvé l'url du fichier OD de référence, qui est https://www.data.gouv.fr/fr/datasets/r/8d9398ae-3037-48b2-be19-412c24561fbb (màj 2022-07-03).

HTH

**Comment by nlehuby** [comment]
Bonjour,

l'analyse actuelle est basée sur le fichier https://www.data.gouv.fr/fr/datasets/r/50625621-18bd-43cb-8fde-6b8c24bdabb3 qui utilise la version 1 du schéma.
Depuis un peu plus d'un an, une nouvelle version du schéma est sortie et est maintenant utilisée en remplacement.

Pour utiliser la version à jour des données, il faudrait au préalable refaire la correspondance entre les différents champs du schéma et les attributs OSM comme ça avait été fait avec la version 1 du schéma : https://wiki.openstreetmap.org/wiki/France/data.gouv.fr/Bornes_de_Recharge_pour_V%C3%A9hicules_%C3%89lectriques

**Comment by nlehuby** [comment]
Le fichier utilisé par Osmose est maintenant à jour :tada: 
Par contre, des évolutions de l'analyse Osmose sont nécessaires (car des champs ont changé de nom mais aussi pour ajouter des infos en plus).
En particulier, il y a un souci avec le `ref:EU:EVSE` qui contenait avant un séparateur et qui n'en a plus maintenant (donc Osmose ne va pas retrouver les éléments précédemment mappés)

En bonus, on peut aussi redresser des noms de réseaux et d'opérateurs tout en majuscule ou autre qu'on ne voudrait pas mettre telquel dans OSM: la liste est ici : https://github.com/Jungle-Bus/ref-EU-EVSE/blob/gh-pages/opendata_networks.csv

**Comment by phd0** [comment]
> En bonus, on peut aussi redresser des noms de réseaux et d'opérateurs tout en majuscule ou autre qu'on ne voudrait pas mettre telquel dans OSM: la liste est ici : https://github.com/Jungle-Bus/ref-EU-EVSE/blob/gh-pages/opendata_networks.csv

j'ai ouvert une issue, sans voir celle ci fermée. 
Par contre, les règles de contrôle osmose n'acceptent pas les noms majuscules, Même pour BMW. 
est t'il possible de diminuer les issues automatiques ?
