### ISSUE TITLE
operator=TotalEnergies Charging Services <> operator=TotalEnergies

### ISSUE THREAD

**Issue by Marc-marc-marc** [Jungle-Bus/ref-EU-EVSE#10]
l'opendata propose d'ajouter operator=TotalEnergies Charging Services
NSI propose de corriger cela en operator=TotalEnergies (ce qui me semble mieux correspondre à la réalité, le nom à ralonge est une marque ou un slogan, pas le nom d'une entreprise

**Comment by nlehuby** [comment]
C'est corrigé, merci du signalement :+1:
