### ISSUE TITLE
ne pas perdre une station si sa ref est invalide

### ISSUE THREAD

**Issue by Marc-marc-marc** [Jungle-Bus/ref-EU-EVSE#19]
je vais un sous-sujet de #11
une station est rejetée parce que la ref est invalide.
je pense qu'il faudrait se contenter de supprimer la ref au lieu de tout rejeter
cela permettrait d'avoir accès à tout le reste via osmose
exemple
ESZUNP8484368745747197865,gireve-2,le format de l'identifiant ref:EU:EVSE (id_station_itinerance) n'est pas valide. Ce point de charge est ignoré et sa station ne sera pas présente dans l'analyse Osmose,"iti: ESZUNP8484368745747197865, local: 1130505"
n’empêche pas de créer https://www.openstreetmap.org/node/12233645448
cette modification nécessaire peut-être un changement préalable pour osmose-backend afin de ne pas l'envoyer dans les choix s'il s'attend à une ref obligatoire

**Comment by guiohm** [comment]
Ce cas est probablement facilement gérable. Personnellement je ne vois pas d'inconvénient à valider des refs non françaises (aussi curieux soit-il)

Pour les autres cas de refs EVSE non valides voir https://github.com/Jungle-Bus/ref-EU-EVSE/issues/17

**Comment by nlehuby** [comment]
on rejette les stations sans ref ou avec une ref invalide parce qu'Osmose a besoin de cet attribut pour chercher des objets dans OSM (cf #17 )

du coup, je ferme ici, cette évolution est à discuter dans l'autre issue.
