### ISSUE TITLE
Conversion des majuscules, lors de l'import des données openDATA

### ISSUE THREAD

**Issue by phd0** [Jungle-Bus/ref-EU-EVSE#5]
bonjour, 
lors de la création des fichiers CVS, la plupart des **name**, et autre **owner** et **network** sont conservés en majuscules (voir même forcé en majuscules pour BMW) or cela génère des _issues_ automatiques dans Osmose par la suite, lors de l'import via le script `analyser_merge_charging_station_FR.py`.
est t'il possible (et souhaitable ?) de convertir les nom en format **Abcdef**, ce qui serait plus simple plutôt que de modifier les règles de contrôle des majuscules.
Je ne suis pas suffisamment doué pour vous proposer un _Pull request_. Pouvez vous me donner votre avis sur ce point ?

![image](https://github.com/Jungle-Bus/ref-EU-EVSE/assets/1939211/d642aa02-e233-45c2-84db-843c6512ced4)
(https://osmose.openstreetmap.fr/fr/issue/818d9803-f056-a2b8-90da-716efde91368)
Philippe

**Comment by nlehuby** [comment]
Bonjour,

je ne pense pas que ça soit souhaitable de modifier automatiquement la casse des données sources : en effet, il s'agit à la base d'une agrégation de multiples jeux de données de producteurs indépendants, et elle est parfois déjà bonne et pourrait être dégradée pour un tel script.

Il est en revanche déjà possible de remplacer les valeurs proposées pour network et operator par d'autres, en modifiant ce fichier csv : https://github.com/Jungle-Bus/ref-EU-EVSE/blob/master/fixes_networks.csv
la première colonne indique le libellé fourni dans le fichier source, et la seconde indique celui à utiliser à la place dans l'analyse Osmose. Par exemple SOREGIES est transformé en Sorégies.
En plus de la casse, cela permet de corriger d'autres anomalies de nommages comme l'accentuation, les abrévations voire les libellés tout simplement fumeux.

Si vous ne souhaitez pas faire la Pull Request, vous pouvez m'indiquer les valeurs que vous souhaiteriez voir modifier ici (valeur actuelle + valeur souhaitée) et je ferai le nécessaire :wink:

**Comment by phd0** [comment]
merci,
j'ai effectivement re-compris comment faire un pull request. C'est bon.

Pour les sujets de majuscules, le fichier CSV que j'avais vu ne correspond donc pas aux règles de contrôle sur osmose. 
il y a par exemple **AlterBase** ; **BMW** ; **MobiVE** ; **SPIE CityNetworks** ; **WiiiZ** ; **MINI** qui posent problème. 
donc soit on bascule en **Bmw** et **Bmw & Mini** (ce qui est super moche) et **Alterbase** (ce qui peut encore passer), soit on modifie les règle de contrôle sur le **tag** _name_, mais aussi _operator_, _owner_ et _network_ mais ça risque fortement de ne pas passer auprès de la communauté. 

En tout état de cause, j'ai arrête d'importer les données openDATA dans OSM via osmose et JOSM, vu que cela va me faire deux fois plus de travail par la suite, sans une prise de position, de personnes plus influentes que moi. 
Philippe

**Comment by nlehuby** [comment]
Pour moi, il n'y a pas vraiment de débat : on ne va pas mettre un nom faux juste pour ne pas avoir d'erreur dans Osmose. Le nom est BMW, donc on met BMW dans OSM. Osmose n'est pas la vérité absolue, et ses règles doivent être changées si elles sont fausses.

Tu as un exemple à me donner stp ?
Normalement, il y a déjà une liste d'exception à cette règle dans Osmose, et il me semble que BMW ne devrait pas remonter en erreur, déjà actuellement.

**Comment by nlehuby** [comment]
pas de news depuis un an, je ferme.
