### ISSUE TITLE
fichier csv manquant

### ISSUE THREAD

**Issue by tykayn** [Jungle-Bus/ref-EU-EVSE#6]
hello,
la doc du wiki indique un csv à ce lien mais je trouve une 404 à la place
https://raw.githubusercontent.com/Jungle-Bus/ref-EU-EVSE/gh-pages/osm_stats.csv

**Comment by nlehuby** [comment]
Bonjour,

En effet, j'avais mis en place ce fichier pour suivre le projet du mois en 2020.
Il comptait 
- le nombre de bornes
- le nombre de bornes pour voitures
- le nombre de bornes pour vélo
- le nombre avec une ref open data
- le nombre avec un tag fixme
- celles qui sont gratuites
- le nombre de places de parking réservées à la recharge. C'est ce dernier chiffre qui est le plus intéressant et qui est à comparer avec les infos open data ou les annonces politiques sur le nombre de points de recharge.

En revanche, le calcul n'a pas été maintenu très longtemps au delà du projet du mois car ce n'est pas trivial à maintenir et que le résultat n'intéresse plus grand monde ;)

Je pense que la dernière version est celle-ci : https://github.com/Jungle-Bus/ref-EU-EVSE/blob/335edcf252ecf439f4427970c15bba330df1e9fa/osm_stats.csv
Peut-être mettre ce lien sur la page de wiki à la place ? 
De manière générale, j'avoue que je ne sais pas trop quoi faire des pages de wiki une fois le projet terminé, ça me semble un peu inévitable que ces pages finissent par référencer des choses qui n'ont plus d'actualité...

**Comment by tykayn** [comment]
merci pour ces éléments, j'ai mis à jour le lien dans le wiki du projet du mois :)
y'a un gens qui s'est amusé à faire des stats aussi tous les jours dans un autre dépot:
https://github.com/BastienGauthier/clean_french_irve

"ça me semble un peu inévitable que ces pages finissent par référencer des choses qui n'ont plus d'actualité..."
oui c'est sûr, après bon, j'ai l'impression que les fournisseurs de données se bougent enfin pour qu'on ait des choses à mettre dans osm. Et Enedis disait qu'ils prévoyaient d'avoir un million de points de charge en 2030, donc je ne sais pas si ce sera un jour fini :D

**Comment by nlehuby** [comment]
Merci pour la correction du wiki.

Le repo que tu pointes fait des stats sur les données open data (alors qu'ici, c'était des stats sur OSM). Mais ça peut être intéressant à suivre en effet : ptet qu'on a envie d'utiliser ce fichier nettoyé plutôt que le fichier brut du PAN ? 

J'avais fait [quelques retours ](https://github.com/etalab/schema-irve/issues/5) au PAN sur des doublons pendant la prépa du projet du mois, mais ça n'avait pas donné lieu à des améliorations de données ...
t'as regardé un peu / t'as un avis sur les mises en qualité effectuées ?

**Comment by nlehuby** [comment]
doc mise à jour https://github.com/Jungle-Bus/ref-EU-EVSE/blob/master/README.md
